- Makefile
- README.md
- cmd/imagor/main.go
- imagorpath/normalize.go
- imagorpath/params.go
- store/filestore/filestore.go
- store/filestore/filestore_test.go
- store/filestore/option.go
- store/s3store/option.go
- store/s3store/s3store.go
- store/s3store/s3store_test.go
https://github.com/cshum/imagor/issues/12
Adding "safe character list" argument for imagorpath.Normalize
> feat(imagorpath) custom shouldEscape func for imagorpath.Normalize

- README.md
- cmd/imagor/main.go
> feat: add s3 force path style option

- README.md
- cmd/imagor/main.go
- imagor.go
- option.go
> feat(imagor): base path redirect option

- README.md
- cmd/imagor/main.go
- imagor.go
- imagor_test.go
- imagorpath/generate.go
- imagorpath/params_test.go
- option.go
> feat(imagor): output WebP format automatically if browser supports

- README.md
> docs: ghcr badge

- imagor_test.go
- imagorpath/parse.go
> fix(imagorpath): hash length for custom signer

- README.md
- config/vipsconfig/vipsconfig.go
- errors.go
- processor/vipsprocessor/image.go
- processor/vipsprocessor/option.go
- processor/vipsprocessor/option_test.go
- processor/vipsprocessor/process.go
- processor/vipsprocessor/vips.go
- processor/vipsprocessor/vips_test.go
Security around so called "image bomb" #22
> feat(vips): vips-max-resolution

- detach.go
- detach_test.go
- imagor.go
- imagor_test.go
improves process response time by detaching save/del from the main context
> feat(imagor): improve process response time

- detach.go
- detach_test.go
- imagor.go
- imagor_test.go
improves process response concurrency by detaching storage put/delete from the main request context
> feat(imagor): improve process response concurrency

- README.md
- app.json
- heroku.yml
- heroku/Dockerfile
For issue #141, create Heroku support for this project.
1. Default value set "IMAGOR_UNSAFE=1" for Testing.
2. Testing and verified on my repo (with repo change).
> #141 Add support for Heroku

- .github/dependabot.yml
- README.md
- blob.go
- blob_test.go
- config/config.go
- fanout.go
- fanout_test.go
- imagor.go
- vips/processor_test.go
simulate seek method for unseekable source with blob.NewReadSeeker
> feat(imagor): blob.NewReadSeeker()

- imagor.go
this may fix some parts of #124
> fix(vips): fix premature end on save for storage

- vips/image.go
- vips/processor.go
- vips/processor_test.go
- vips/vips.go
fixes some of the file system context issues #162
> fix(vips): fix file context and cleanup

- blob.go
- blob_test.go
- vips/processor_test.go
#162 fix blob reader left unclosed
> fix(imagor): fix blob reader close

- config/awsconfig/awsconfig.go
- config/awsconfig/awsconfig_test.go
> feat(awsconfig): different AWS credentials for Loader, Storage, Results Storage

- config/awsconfig/awsconfig.go
- config/awsconfig/awsconfig_test.go
> fix(awsconfig): accept default credentials

- config/awsconfig/awsconfig.go
> feat(awsconfig): AWS config shared credentials

- loader/httploader/httploader.go
- loader/httploader/httploader_test.go
This changes the behavior of imagor to also respect HTTP loader allowed sources flag for HTTP redirects.  Even a trusted source can be compromised and we don't want that source to start redirecting to disallowed sources.
> forbid redirects to non allowed URLs

- imagor.go
- imagor_test.go
> feat(imagor): expire(timstamp) filter

- config/config.go
- config/config_test.go
- imagor.go
- imagor_test.go
- option.go
> feat(imagor): retry query unescape on invalid path

- vips/process.go
> refactor(vips): remove LockOsThread in Process

- vips/processor.go
> fix(vips): should not fail on error

- imagor.go
- imagor_test.go
> feat(imagor): Vary: Accept response header on auto webp

- config/config_test.go
- config/httpconfig.go
- go.mod
- loader/httploader/httploader.go
- loader/httploader/httploader_test.go
- loader/httploader/option.go
> feat(httploader): base URL option for HTTP Loader

- vips/foreign.c
> fix(vips): fix default profile for webp save

- fanoutreader/fanout.go
When readAll tries to push data to channel it's doing it under the fanout lock which can deadlock with reader Close that also tried to acquire that lock before signaling that channel is closed.
This change resolves this by using the cancellation channel pattern.
Fixes #349
> Fix deadlock in fanout reader between data reading goroutine and Close

- Dockerfile
To fix: https://github.com/cshum/imagor/issues/368
Source: https://github.com/libvips/libvips/issues/2713
> fix(build): Docker add liblcms2

- README.md
- config/awsconfig/awsconfig.go
- config/fileconfig.go
- config/gcloudconfig/gcloudconfig.go
- imagorpath/normalize.go
- imagorpath/params_test.go
- storage/filestorage/filestorage_test.go
- storage/gcloudstorage/gcloudstorage_test.go
- storage/s3storage/s3storage.go
- storage/s3storage/s3storage_test.go
> feat: no-op safe chars

- server/handler.go
- server/server.go
> refactor: exclude healthcheck from access logs

- blob.go
- config/config_test.go
- config/httpconfig.go
- imagor.go
- imagor_test.go
- loader/httploader/httploader.go
- loader/httploader/httploader_test.go
- loader/httploader/option.go
> feat: override response header option for HTTP Loader

- imagor.go
- imagor_test.go
> fix: fix override header for processed blob

- storage/filestorage/filestorage.go
> fix(filestorage): sync and attempt delete file on error

- .github/workflows/test.yml
- Dockerfile
> build: update libheif1 from bookworm-backports

- storage/s3storage/s3storage.go
- storage/s3storage/s3storage_test.go
> fix: normalize leading slash for s3 path

- storage/s3storage/s3storage.go
This should solve the warnings reported here: https://github.com/cshum/imagor/issues/593
> Disable log output checksum validation for S3

- imagor.go
- imagor_test.go
Hello @cshum,
I was implementing a setup where I use separate GCS buckets for source images and result caching (no http loader), and encountered a limitation with the existing modified time check functionality:
The current `--imagor-modified-time-check` feature only checks modification times via storage stat operations. However, when using GCS as the loader (source bucket, read-only) with a different GCS bucket for result storage, there's no way to perform stat operations on the source images for comparison.
This creates a scenario where:
1. Images are loaded from GCS bucket A (read-only source) via a loader
2. Results are cached in GCS bucket B via result storage
3. Modified time checks can't determine if source images in bucket A have been updated
4. Stale cached results may be served …
> feat: implement Stater interface for loaders and enhance modified time check logic

- .github/workflows/docker-imagor-variants.yml
- .github/workflows/docker-variants.yml
- Dockerfile
- README.md
> build(docker): Docker mozjpeg variant for imagor

- storage/gcloudstorage/gcloudstorage.go
- storage/gcloudstorage/gcloudstorage_test.go
Hello @cshum,
stumbled up-on another issue in my environment:
When GCS objects are stored with gzip compression, the fanout reader was being initialized with the compressed size from `attrs.Size`, but GCS automatically decompresses content during reads. This size mismatch caused the fanout reader to allocate an undersized buffer, leading to truncated reads that appeared as imagor failures.
- `attrs.Size` contains the compressed size for gzip-encoded objects
- GCS reader auto-decompresses on the fly, resulting in larger actual content
- Fanout reader allocated buffer based on compressed size → buffer overflow/truncation
- Skip fanout optimization for gzip-compressed objects (`attrs.ContentEncoding == "gzip"`)
- When `size = 0`, fanout reader is disabled and standard readers are used …
> GCS loader fix
